#!/bin/bash
if [[ "$OSTYPE" == "darwin"* ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
SCRIPTPATH=$($READLINK -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
PROJECTDIR=$(dirname $SCRIPTDIR)

cabal exec runhaskell -- \
  -i$PROJECTDIR/src/spec \
  -i$PROJECTDIR/src/lib \
  $PROJECTDIR/src/spec/Spec.hs

